/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author Acer
 */
public class FormRiwayatTransaksi extends javax.swing.JFrame {

    private DefaultTableModel model;
    private JTable table;

    private JTextField txtCariNama;
    private JDateChooser dateChooser;
    private JButton btFilter;

    public FormRiwayatTransaksi() {
        setTitle("Riwayat Transaksi");
        setSize(1000, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout()); // penting!

        // Panel filter di atas
        JPanel panelFilter = new JPanel();
        txtCariNama = new JTextField(15);
        dateChooser = new JDateChooser();
        btFilter = new JButton("Filter");

        panelFilter.add(new JLabel("Nama Pelanggan:"));
        panelFilter.add(txtCariNama);
        panelFilter.add(new JLabel("Tanggal:"));
        panelFilter.add(dateChooser);
        panelFilter.add(btFilter);

        add(panelFilter, BorderLayout.NORTH);

        // Kolom tabel
        String[] columnNames = {
            "ID Transaksi", "Tanggal", "Nama Pelanggan", "Nama Pegawai",
            "Subtotal", "Pajak", "Service", "Diskon", "Grand Total"
        };
        model = new DefaultTableModel(columnNames, 0);
        table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);

        // Listener tombol filter
        btFilter.addActionListener(e -> {
            String nama = txtCariNama.getText().trim();
            String tanggal = "";
            if (dateChooser.getDate() != null) {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                tanggal = sdf.format(dateChooser.getDate());
            }
            loadData(nama, tanggal);
        });

        // Load data awal tanpa filter
        loadData("", "");

        setVisible(true);
    }
    
    // Versi loadData dengan parameter filter
    public void loadData(String namaFilter, String tanggalFilter) {
        model.setRowCount(0);
        String sql = "SELECT * FROM transaksi WHERE 1=1";

        if (!namaFilter.isEmpty()) {
            sql += " AND namapelanggan LIKE '%" + namaFilter + "%'";
        }
        if (!tanggalFilter.isEmpty()) {
            sql += " AND tgltransaksi = '" + tanggalFilter + "'";
        }
        sql += " ORDER BY idtransaksi ASC";

        try (Connection conn = dbkoneksi.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                Object[] row = new Object[]{
                    rs.getString("idtransaksi"),
                    rs.getString("tgltransaksi"),
                    rs.getString("namapelanggan"),
                    rs.getString("namapegawai"),
                    rs.getInt("subtotal"),
                    rs.getInt("pajak"),
                    rs.getInt("service"),
                    rs.getInt("diskon"),
                    rs.getInt("grandtotal")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRiwayatTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
